/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * welcom.java
 *
 * Created on Aug 10, 2017, 6:47:35 PM
 */

package donaire;

import MyFrames.Frame1;
import MyFrames2.Frame2;
import MyFrames2.Frame3;
import MyFrames2.Frame4;
import java.awt.Desktop;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Elgane Ongcoy
 */
public class welcom extends javax.swing.JFrame {

    /** Creates new form welcom */
    public welcom() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstnamejTextField2 = new javax.swing.JTextField();
        lastnamejTextField3 = new javax.swing.JTextField();
        agejTextField4 = new javax.swing.JTextField();
        addressjTextField5 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        savejButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        updatejButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        deletejButton3 = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        refreshjButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        coursejTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        labellMessage = new javax.swing.JLabel();
        searchjTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        genderjComboBox1 = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        filejMenu1le = new javax.swing.JMenu();
        exitjMenuItem1 = new javax.swing.JMenuItem();
        frame1jMenu1 = new javax.swing.JMenu();
        frame1jMenuItem1 = new javax.swing.JMenuItem();
        frame2 = new javax.swing.JMenu();
        frame2jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        frame3jMenuItem1 = new javax.swing.JMenuItem();
        frame4jMenu2 = new javax.swing.JMenu();
        frame4jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jDesktopPane1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Firstname :");
        jDesktopPane1.add(jLabel2);
        jLabel2.setBounds(40, 90, 80, 20);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Lastname :");
        jDesktopPane1.add(jLabel3);
        jLabel3.setBounds(40, 120, 80, 20);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Age :");
        jDesktopPane1.add(jLabel4);
        jLabel4.setBounds(80, 150, 50, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel5.setText("Address :");
        jDesktopPane1.add(jLabel5);
        jLabel5.setBounds(60, 180, 70, 30);
        jDesktopPane1.add(firstnamejTextField2);
        firstnamejTextField2.setBounds(120, 90, 330, 20);
        jDesktopPane1.add(lastnamejTextField3);
        lastnamejTextField3.setBounds(120, 120, 330, 20);
        jDesktopPane1.add(agejTextField4);
        agejTextField4.setBounds(120, 150, 330, 20);
        jDesktopPane1.add(addressjTextField5);
        addressjTextField5.setBounds(120, 190, 330, 20);

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Firstname", "Lastname", "Age", "Address", "Course", "Gender"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jDesktopPane1.add(jScrollPane1);
        jScrollPane1.setBounds(460, 90, 530, 330);

        jToolBar1.setBackground(new java.awt.Color(204, 204, 255));
        jToolBar1.setRollover(true);

        savejButton1.setBackground(new java.awt.Color(204, 255, 255));
        savejButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        savejButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donaire/save.png"))); // NOI18N
        savejButton1.setText("Save");
        savejButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(savejButton1);
        jToolBar1.add(jSeparator1);

        updatejButton2.setBackground(new java.awt.Color(255, 204, 255));
        updatejButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        updatejButton2.setText("Update");
        updatejButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(updatejButton2);
        jToolBar1.add(jSeparator2);
        jToolBar1.add(jSeparator3);

        deletejButton3.setBackground(new java.awt.Color(255, 255, 204));
        deletejButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        deletejButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/donaire/delete.png"))); // NOI18N
        deletejButton3.setText("Delete");
        deletejButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletejButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(deletejButton3);
        jToolBar1.add(jSeparator4);

        refreshjButton4.setBackground(new java.awt.Color(204, 255, 204));
        refreshjButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        refreshjButton4.setText("Refresh");
        jToolBar1.add(refreshjButton4);

        jDesktopPane1.add(jToolBar1);
        jToolBar1.setBounds(10, 10, 310, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Course :");
        jDesktopPane1.add(jLabel6);
        jLabel6.setBounds(60, 210, 70, 30);
        jDesktopPane1.add(coursejTextField6);
        coursejTextField6.setBounds(120, 220, 330, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("GENDER");
        jDesktopPane1.add(jLabel7);
        jLabel7.setBounds(230, 270, 90, 22);

        labellMessage.setBackground(new java.awt.Color(255, 51, 0));
        labellMessage.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        labellMessage.setForeground(new java.awt.Color(255, 51, 0));
        jDesktopPane1.add(labellMessage);
        labellMessage.setBounds(420, 50, 410, 30);

        searchjTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchjTextField1KeyReleased(evt);
            }
        });
        jDesktopPane1.add(searchjTextField1);
        searchjTextField1.setBounds(410, 10, 443, 28);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel1.setText("Search :");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(340, 10, 70, 20);

        genderjComboBox1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        genderjComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MALE", "FEMALE", "", "" }));
        genderjComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderjComboBox1ActionPerformed(evt);
            }
        });
        jDesktopPane1.add(genderjComboBox1);
        genderjComboBox1.setBounds(130, 300, 280, 23);

        filejMenu1le.setText("File");

        exitjMenuItem1.setText("Exit");
        exitjMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitjMenuItem1ActionPerformed(evt);
            }
        });
        filejMenu1le.add(exitjMenuItem1);

        jMenuBar1.add(filejMenu1le);

        frame1jMenu1.setText("frame1");

        frame1jMenuItem1.setText("frame");
        frame1jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame1jMenuItem1ActionPerformed(evt);
            }
        });
        frame1jMenu1.add(frame1jMenuItem1);

        jMenuBar1.add(frame1jMenu1);

        frame2.setText("frame2");
        frame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame2ActionPerformed(evt);
            }
        });

        frame2jMenuItem1.setText("frame2");
        frame2jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame2jMenuItem1ActionPerformed(evt);
            }
        });
        frame2.add(frame2jMenuItem1);

        jMenuBar1.add(frame2);

        jMenu1.setText("frame3");

        frame3jMenuItem1.setText("frame3");
        frame3jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame3jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(frame3jMenuItem1);

        jMenuBar1.add(jMenu1);

        frame4jMenu2.setText("frame4");

        frame4jMenuItem1.setText("frame4");
        frame4jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                frame4jMenuItem1ActionPerformed(evt);
            }
        });
        frame4jMenu2.add(frame4jMenuItem1);

        jMenuBar1.add(frame4jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savejButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButton1ActionPerformed
   DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        labellMessage.setText("");
        if (!firstnamejTextField2.getText().trim().equals("")) {
            if (!lastnamejTextField3.getText().trim().equals("")) {
                if (!agejTextField4.getText().trim().equals("")) {
                    if (!addressjTextField5.getText().trim().equals("")) {
                        if (!coursejTextField6.getText().trim().equals("")) {
                    
                
                    model.addRow(new Object[]{firstnamejTextField2.getText(),lastnamejTextField3.getText(),agejTextField4.getText(), addressjTextField5.getText(), coursejTextField6.getText(), genderjComboBox1.getSelectedItem().toString()});
                } else {
                    labellMessage.setText("course Dont left blank");
                }
            } else {
                labellMessage.setText("address Dont left blank");
            }

        } else {
            labellMessage.setText("age Dont left blank");
        }
} else {
            labellMessage.setText("lastname Dont left blank");
        }
            } else {
            labellMessage.setText("firstname Dont left blank");
        }



    }//GEN-LAST:event_savejButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        firstnamejTextField2.setText(model.getValueAt(jTable1.getSelectedRow(), 0).toString());
        lastnamejTextField3.setText(model.getValueAt(jTable1.getSelectedRow(), 1).toString());
       agejTextField4.setText(model.getValueAt(jTable1.getSelectedRow(), 2).toString());
         addressjTextField5.setText(model.getValueAt(jTable1.getSelectedRow(), 3).toString());
           coursejTextField6.setText(model.getValueAt(jTable1.getSelectedRow(), 4).toString());


    }//GEN-LAST:event_jTable1MouseClicked

    private void deletejButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletejButton3ActionPerformed
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        labellMessage.setText("");
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                labellMessage.setText("Table is empty");
            } else {

                labellMessage.setText("You must select on the table to delete");

            }
        } else {
            model.removeRow(jTable1.getSelectedRow());
    }                                             
    }//GEN-LAST:event_deletejButton3ActionPerformed

    private void updatejButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButton2ActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        labellMessage.setText("");
        if (jTable1.getSelectedRow() == -1) {
            if (jTable1.getRowCount() == 0) {
                labellMessage.setText("Table is empty");
            } else {

                labellMessage.setText("You must select on the table to update");

            }
        } else {
            model.setValueAt(firstnamejTextField2.getText(), jTable1.getSelectedRow(), 0);
            model.setValueAt(lastnamejTextField3.getText(), jTable1.getSelectedRow(), 1);
            model.setValueAt(agejTextField4.getText(), jTable1.getSelectedRow(), 2);
            model.setValueAt(addressjTextField5.getText(), jTable1.getSelectedRow(), 3);
            model.setValueAt(coursejTextField6.getText(), jTable1.getSelectedRow(), 4);
             model.setValueAt(genderjComboBox1.getSelectedItem(), jTable1.getSelectedRow(), 5);
        }
    }//GEN-LAST:event_updatejButton2ActionPerformed

    private void genderjComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderjComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderjComboBox1ActionPerformed

    private void searchjTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchjTextField1KeyReleased

    }//GEN-LAST:event_searchjTextField1KeyReleased

    private void exitjMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitjMenuItem1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitjMenuItem1ActionPerformed

    private void frame1jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame1jMenuItem1ActionPerformed
        Frame1 f = new Frame1();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_frame1jMenuItem1ActionPerformed

    private void frame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame2ActionPerformed
  
    }//GEN-LAST:event_frame2ActionPerformed

    private void frame2jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame2jMenuItem1ActionPerformed
         Frame2 g = new Frame2();
        jDesktopPane1.add(g);
        g.setVisible(true);
    }//GEN-LAST:event_frame2jMenuItem1ActionPerformed

    private void frame3jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame3jMenuItem1ActionPerformed
       Frame3 f = new Frame3();
        jDesktopPane1.add(f);
        f.setVisible(true);
    }//GEN-LAST:event_frame3jMenuItem1ActionPerformed

    private void frame4jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_frame4jMenuItem1ActionPerformed
         Frame4 h = new Frame4();
        jDesktopPane1.add(h);
        h.setVisible(true);
    }//GEN-LAST:event_frame4jMenuItem1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new welcom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressjTextField5;
    private javax.swing.JTextField agejTextField4;
    private javax.swing.JTextField coursejTextField6;
    private javax.swing.JButton deletejButton3;
    private javax.swing.JMenuItem exitjMenuItem1;
    private javax.swing.JMenu filejMenu1le;
    private javax.swing.JTextField firstnamejTextField2;
    private javax.swing.JMenu frame1jMenu1;
    private javax.swing.JMenuItem frame1jMenuItem1;
    private javax.swing.JMenu frame2;
    private javax.swing.JMenuItem frame2jMenuItem1;
    private javax.swing.JMenuItem frame3jMenuItem1;
    private javax.swing.JMenu frame4jMenu2;
    private javax.swing.JMenuItem frame4jMenuItem1;
    private javax.swing.JComboBox genderjComboBox1;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JTable jTable1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labellMessage;
    private javax.swing.JTextField lastnamejTextField3;
    private javax.swing.JButton refreshjButton4;
    private javax.swing.JButton savejButton1;
    private javax.swing.JTextField searchjTextField1;
    private javax.swing.JButton updatejButton2;
    // End of variables declaration//GEN-END:variables

}
